//Gabriel Riul Perissé
//RA: 2064430

import java.util.ArrayList;
import javax.swing.JOptionPane;

public class FormPrincipal extends javax.swing.JFrame {
    
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPrincipal = new javax.swing.JLabel();
        buttonSair = new javax.swing.JButton();
        barraPrincipal = new javax.swing.JMenuBar();
        menuUsuário = new javax.swing.JMenu();
        itMenuGestor = new javax.swing.JMenuItem();
        itMenuProfessor = new javax.swing.JMenuItem();
        itMenuAluno = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bibliotech 2.0");
        setPreferredSize(new java.awt.Dimension(400, 285));

        labelPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelPrincipal.setText("PRINCIPAL");

        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        menuUsuário.setText("Usuário");

        itMenuGestor.setText("Gestor");
        itMenuGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuGestorActionPerformed(evt);
            }
        });
        menuUsuário.add(itMenuGestor);

        itMenuProfessor.setText("Professor");
        itMenuProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuProfessorActionPerformed(evt);
            }
        });
        menuUsuário.add(itMenuProfessor);

        itMenuAluno.setText("Aluno");
        itMenuAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuAlunoActionPerformed(evt);
            }
        });
        menuUsuário.add(itMenuAluno);

        barraPrincipal.add(menuUsuário);

        setJMenuBar(barraPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonSair)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPrincipal)
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(labelPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(buttonSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMenuGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuGestorActionPerformed
        abraFormGestor();
    }//GEN-LAST:event_itMenuGestorActionPerformed

    private void itMenuProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuProfessorActionPerformed
        abraFormProfessor();
    }//GEN-LAST:event_itMenuProfessorActionPerformed

    private void itMenuAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuAlunoActionPerformed
        abraFormAluno();
    }//GEN-LAST:event_itMenuAlunoActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        sair();
    }//GEN-LAST:event_buttonSairActionPerformed

    public void abraFormGestor(){
        FormGestor.geraGestor().setVisible(true);
    }
    
    public void abraFormProfessor(){
        FormProfessor.geraProf().setVisible(true);
    }
    
    public void abraFormAluno(){
        FormAluno.geraAluno().setVisible(true);
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Confirmação de Saída",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            System.exit(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraPrincipal;
    private javax.swing.JButton buttonSair;
    private javax.swing.JMenuItem itMenuAluno;
    private javax.swing.JMenuItem itMenuGestor;
    private javax.swing.JMenuItem itMenuProfessor;
    private javax.swing.JLabel labelPrincipal;
    private javax.swing.JMenu menuUsuário;
    // End of variables declaration//GEN-END:variables
}
